name: pokeapi
description: PokeAPI Package
version: 1.0.2
author: Supitsara Prathan <prathanbomb@gmail.com>
homepage: "https://github.com/prathanbomb/pokedart"

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.8
